
package IGU;

import Logica.Agenda;

/**
 *
 * @author Gonzalo Ramirez
 */
public class AgendaInterface extends javax.swing.JFrame {

        /**
     * @param args the command line arguments
     */

    Agenda agenda;
    /**
     * Creates new form AgendaInterface
     */
    public AgendaInterface() {
        initComponents();
        agenda = new Agenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        tituloAgenda = new javax.swing.JLabel();
        dniText = new javax.swing.JLabel();
        nombreText = new javax.swing.JLabel();
        apellidoText = new javax.swing.JLabel();
        direccionText = new javax.swing.JLabel();
        telefonoText = new javax.swing.JLabel();
        fecNacText = new javax.swing.JLabel();
        grabar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        indiceText = new javax.swing.JLabel();
        dniCampo = new javax.swing.JTextField();
        nombreCampo = new javax.swing.JTextField();
        apellidoCampo = new javax.swing.JTextField();
        direccionCampo = new javax.swing.JTextField();
        telefonoCampo = new javax.swing.JTextField();
        fecNacCampo = new javax.swing.JTextField();
        indice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloAgenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloAgenda.setForeground(new java.awt.Color(0, 0, 100));
        tituloAgenda.setText("AGENDA ELECTRÓNICA");

        dniText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dniText.setForeground(new java.awt.Color(0, 0, 100));
        dniText.setText("DNI      :");

        nombreText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreText.setForeground(new java.awt.Color(0, 0, 100));
        nombreText.setText("Nombre:");

        apellidoText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apellidoText.setForeground(new java.awt.Color(0, 0, 100));
        apellidoText.setText("Apellido:");

        direccionText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        direccionText.setForeground(new java.awt.Color(0, 0, 100));
        direccionText.setText("Direccion:");

        telefonoText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telefonoText.setForeground(new java.awt.Color(0, 0, 100));
        telefonoText.setText("Telefono:");

        fecNacText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fecNacText.setForeground(new java.awt.Color(0, 0, 100));
        fecNacText.setText("F. Nac    :");

        grabar.setText("Grabar");
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });

        siguiente.setText(">>");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        atras.setText("<<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        indiceText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        indiceText.setText("Indice:");

        dniCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniCampoActionPerformed(evt);
            }
        });

        nombreCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCampoActionPerformed(evt);
            }
        });

        apellidoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoCampoActionPerformed(evt);
            }
        });

        direccionCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionCampoActionPerformed(evt);
            }
        });

        telefonoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoCampoActionPerformed(evt);
            }
        });

        fecNacCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecNacCampoActionPerformed(evt);
            }
        });

        indice.setEditable(false);
        indice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        indice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        indice.setText("0");
        indice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(separador2)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreText)
                            .addComponent(apellidoText)
                            .addComponent(dniText))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dniCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(nombreCampo)
                            .addComponent(apellidoCampo))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecNacText)
                            .addComponent(direccionText)
                            .addComponent(telefonoText))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(direccionCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(telefonoCampo)
                            .addComponent(fecNacCampo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(indiceText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(atras)
                                .addGap(55, 55, 55)
                                .addComponent(grabar)))
                        .addGap(42, 42, 42)
                        .addComponent(siguiente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(tituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniText)
                    .addComponent(direccionText)
                    .addComponent(dniCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreText)
                    .addComponent(telefonoText)
                    .addComponent(nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoText)
                    .addComponent(fecNacText)
                    .addComponent(apellidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecNacCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grabar)
                    .addComponent(siguiente)
                    .addComponent(atras))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indiceText)
                    .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniCampoActionPerformed
        dniCampo.setText(agenda.dniRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_dniCampoActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        //if para que no pase a menos de 0 y se actualizan los datos de cada campo de texto
        if(agenda.valorIndice()>0){
            int aux=agenda.valorIndice();
            aux--;
            agenda.cambiarIndice(aux);
            indice.setText(""+aux);
            dniCampo.setText(agenda.dniRetorna(agenda.valorIndice()));
            nombreCampo.setText(agenda.nombreRetorna(agenda.valorIndice()));
            apellidoCampo.setText(agenda.apellidoRetorna(agenda.valorIndice()));
            direccionCampo.setText(agenda.direccionRetorna(agenda.valorIndice()));
            telefonoCampo.setText(agenda.telefonoRetorna(agenda.valorIndice()));
            fecNacCampo.setText(agenda.fecNacRetorna(agenda.valorIndice()));
        }
        
    }//GEN-LAST:event_atrasActionPerformed

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        //se guardan los datos puestos en los campos
        String dni=dniCampo.getText();
        String nombre=nombreCampo.getText();
        String apellido=apellidoCampo.getText();
        String direccion=direccionCampo.getText();
        String telefono=telefonoCampo.getText();
        String fecNac=fecNacCampo.getText();
        
        agenda.dniGuardar(dni, agenda.valorIndice());
        agenda.nombreGuardar(nombre, agenda.valorIndice());
        agenda.apellidoGuardar(apellido, agenda.valorIndice());
        agenda.direccionGuardar(direccion, agenda.valorIndice());
        agenda.telefooGuardar(telefono, agenda.valorIndice());
        agenda.fecNacGuardar(fecNac, agenda.valorIndice());
    }//GEN-LAST:event_grabarActionPerformed

    private void nombreCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCampoActionPerformed
        nombreCampo.setText(agenda.nombreRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_nombreCampoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
       //Se verifica que no sobrepase el numero 9 y se actualizan los datos
        if(agenda.valorIndice()<=8){
            int aux =agenda.valorIndice();
            aux++;
            agenda.cambiarIndice(aux);
            indice.setText(""+aux);
            dniCampo.setText(agenda.dniRetorna(agenda.valorIndice()));
            nombreCampo.setText(agenda.nombreRetorna(agenda.valorIndice()));
            apellidoCampo.setText(agenda.apellidoRetorna(agenda.valorIndice()));
            direccionCampo.setText(agenda.direccionRetorna(agenda.valorIndice()));
            telefonoCampo.setText(agenda.telefonoRetorna(agenda.valorIndice()));
            fecNacCampo.setText(agenda.fecNacRetorna(agenda.valorIndice()));
            
        }
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void apellidoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoCampoActionPerformed
       apellidoCampo.setText(agenda.apellidoRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_apellidoCampoActionPerformed

    private void direccionCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionCampoActionPerformed
        direccionCampo.setText(agenda.direccionRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_direccionCampoActionPerformed

    private void telefonoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoCampoActionPerformed
        telefonoCampo.setText(agenda.telefonoRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_telefonoCampoActionPerformed

    private void fecNacCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecNacCampoActionPerformed
        fecNacCampo.setText(agenda.fecNacRetorna(agenda.valorIndice()));
    }//GEN-LAST:event_fecNacCampoActionPerformed

    private void indiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceActionPerformed
        indice.setText(""+agenda.valorIndice());
    }//GEN-LAST:event_indiceActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoCampo;
    private javax.swing.JLabel apellidoText;
    private javax.swing.JButton atras;
    private javax.swing.JTextField direccionCampo;
    private javax.swing.JLabel direccionText;
    private javax.swing.JTextField dniCampo;
    private javax.swing.JLabel dniText;
    private javax.swing.JTextField fecNacCampo;
    private javax.swing.JLabel fecNacText;
    private javax.swing.JButton grabar;
    private javax.swing.JTextField indice;
    private javax.swing.JLabel indiceText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreCampo;
    private javax.swing.JLabel nombreText;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField telefonoCampo;
    private javax.swing.JLabel telefonoText;
    private javax.swing.JLabel tituloAgenda;
    // End of variables declaration//GEN-END:variables

    private void actualizar(){}


}
